DROP TABLE VIDEO_ACTOR;
DROP TABLE VIDEO;
DROP TABLE ACTOR;
DROP TABLE FOLDER;
DROP TABLE COMMUNICATION_TRANSACTION;
DROP TABLE COMMUNICATION_REQUEST_CONTENT;
DROP TABLE COMMUNICATION_RESPONSE_CONTENT;

exit;