DROP SEQUENCE ACTOR_SEQ;
DROP SEQUENCE VIDEO_SEQ;
DROP SEQUENCE FOLDER_SEQ;
DROP SEQUENCE COMMUNICATION_TRANSACTION_SEQ;
DROP SEQUENCE COMMUNICATION_REQUEST_CONTENT_SEQ;
DROP SEQUENCE COMMUNICATION_RESPONSE_CONTENT_SEQ;

exit;