CREATE TABLE ACTOR (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(256) UNIQUE NOT NULL,
    STATUS VARCHAR2(128) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE ACTOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

exit;