CREATE TABLE VIDEO (
    ID NUMBER PRIMARY KEY,
    FOLDER_ID NUMBER REFERENCES FOLDER(ID) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    FILE_SIZE VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(128) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE VIDEO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

exit;