CREATE TABLE VIDEO_ACTOR (
    VIDEO_ID NUMBER NOT NULL,
    ACTOR_ID NUMBER NOT NULL,
    PRIMARY KEY (VIDEO_ID, ACTOR_ID),
    FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ID) ON DELETE CASCADE
);

exit;