CREATE TABLE COMMUNICATION_TRANSACTION (
    ID NUMBER PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(256) UNIQUE NOT NULL,
    REQUESTED_PATH VARCHAR2(256) NOT NULL,
    SENDER_IP VARCHAR2(64) NOT NULL,
    REQUEST_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RESPONSE_AT TIMESTAMP
);

CREATE UNIQUE INDEX INDEX_COMMUNICATION_TRANSACTION_TRANSACTION_ID
  ON COMMUNICATION_TRANSACTION (TRANSACTION_ID);

CREATE SEQUENCE COMMUNICATION_TRANSACTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

exit;