CREATE TABLE COMMUNICATION_RESPONSE_CONTENT (
    ID NUMBER PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(256) UNIQUE NOT NULL,
    CONTENT CLOB NOT NULL,
    CONSTRAINT FK_COMMUNICATION_RESPONSE_CONTENT_TRANSACTION_ID
        FOREIGN KEY (TRANSACTION_ID)
        REFERENCES COMMUNICATION_TRANSACTION(TRANSACTION_ID)
);

CREATE SEQUENCE COMMUNICATION_RESPONSE_CONTENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

exit;